<?php
require_once __DIR__.'/config/config.php';
try {
  $settings=db()->query('SELECT * FROM settings WHERE id=1')->fetch() ?: [];
  $products=db()->query('SELECT p.*, (SELECT image FROM product_images pi WHERE pi.product_id=p.id ORDER BY sort_order,id LIMIT 1) AS image FROM products p WHERE p.available=1 ORDER BY p.id DESC')->fetchAll();
  $kits=db()->query('SELECT * FROM kits WHERE available=1 ORDER BY id DESC')->fetchAll();
  $testimonials=db()->query('SELECT * FROM testimonials WHERE published=1 ORDER BY id DESC')->fetchAll();
  $faqs=db()->query('SELECT * FROM faqs WHERE published=1 ORDER BY id')->fetchAll();
  $trainings=db()->query('SELECT * FROM trainings WHERE published=1 ORDER BY id DESC')->fetchAll();
} catch(Throwable $e){$settings=['site_name'=>'Nova Business','logo'=>'assets/logo.svg','phone'=>'+225 07 00 00 00 00','whatsapp'=>'2250700000000','hero_title'=>'Développez une activité qui vous ressemble.','hero_text'=>'Découvrez notre opportunité, nos produits et l’accompagnement proposé pour vous lancer sereinement.'];$products=$kits=$testimonials=$faqs=$trainings=[];}
$name=$settings['site_name']??'Nova Business'; $logo=$settings['logo']??'assets/logo.svg'; $phone=$settings['phone']??''; $wa=preg_replace('/\D+/','',$settings['whatsapp']??'2250700000000');
function wa_link($text='Bonjour, je souhaite en savoir plus sur votre activité.'){global $wa;return 'https://wa.me/'.$wa.'?text='.rawurlencode($text);}
function money($v){return $v===null||$v===''?'Sur demande':number_format((float)$v,0,',',' ').' FCFA';}
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="<?=e($name)?> — opportunité, produits et accompagnement."><title><?=e($name)?></title><link rel="stylesheet" href="assets/style.css"></head><body>
<header><a class="brand" href="#"><img src="<?=e($logo)?>" alt="Logo"><span><?=e($name)?></span></a><nav><a href="#opportunite">L’opportunité</a><a href="#kits">Kits</a><a href="#produits">Produits</a><a href="#accompagnement">Accompagnement</a><a href="#faq">FAQ</a></nav><a class="btn small" href="<?=e(wa_link())?>">WhatsApp</a></header>
<main><section class="hero"><div><span class="eyebrow">OPPORTUNITÉ • PRODUITS • ACCOMPAGNEMENT</span><h1><?=e($settings['hero_title']??'Développez une activité qui vous ressemble.')?></h1><p><?=nl2br(e($settings['hero_text']??''))?></p><div class="actions"><a class="btn" href="<?=e(wa_link('Bonjour, je souhaite devenir partenaire et découvrir le projet.'))?>">Devenir partenaire</a><a class="btn ghost" href="#produits">Découvrir les produits</a></div></div><div class="hero-card"><div class="orb"></div><strong>Une plateforme pensée pour convertir.</strong><p>Présenter. Rassurer. Qualifier. Contacter. Convertir.</p></div></section>
<section id="opportunite" class="section"><span class="eyebrow">L’OPPORTUNITÉ</span><h2>Deux façons de profiter du projet</h2><div class="grid two"><article><b>01 — Devenir partenaire</b><h3>Développer l’activité</h3><p>Présentez le projet, démarrez avec un kit puis bénéficiez d’une formation et d’un accompagnement.</p><a href="<?=e(wa_link('Bonjour, je veux devenir partenaire. Pouvez-vous m’expliquer le fonctionnement ?'))?>">En savoir plus →</a></article><article><b>02 — Découvrir les produits</b><h3>Consommer simplement</h3><p>Découvrez les produits disponibles et contactez-nous si vous souhaitez en savoir plus ou commander.</p><a href="#produits">Voir les produits →</a></article></div></section>
<section id="accompagnement" class="section dark"><span class="eyebrow">LE PARCOURS</span><h2>Un parcours simple et humain</h2><div class="steps"><div><b>01</b><h3>Découvrir</h3><p>Comprendre le projet et les produits.</p></div><div><b>02</b><h3>Échanger</h3><p>Poser vos questions directement.</p></div><div><b>03</b><h3>Démarrer</h3><p>Choisir la formule adaptée.</p></div><div><b>04</b><h3>Être accompagné</h3><p>Recevoir formation et suivi.</p></div></div></section>
<section id="kits" class="section"><span class="eyebrow">KITS</span><h2>Kits de démarrage</h2><?php if($kits):?><div class="grid three"><?php foreach($kits as $k):?><article class="item-card"><?php if($k['image']):?><img src="<?=e($k['image'])?>" alt="<?=e($k['name'])?>"><?php endif;?><h3><?=e($k['name'])?></h3><p><?=nl2br(e($k['description']))?></p><strong><?=e(money($k['price']))?></strong><a class="btn small" href="<?=e(wa_link('Bonjour, je suis intéressé par le kit '.$k['name'].'.'))?>">En savoir plus</a></article><?php endforeach;?></div><?php else:?><div class="empty"><span>Les kits seront ajoutés par l’administrateur.</span><small>Chaque kit pourra avoir ses photos, son contenu, son prix et sa disponibilité.</small></div><?php endif;?></section>
<section id="produits" class="section alt"><span class="eyebrow">PRODUITS</span><h2>Découvrez les produits</h2><?php if($products):?><div class="grid three"><?php foreach($products as $p):?><article class="item-card"><?php if($p['image']):?><img src="<?=e($p['image'])?>" alt="<?=e($p['name'])?>"><?php endif;?><h3><?=e($p['name'])?></h3><p><?=nl2br(e($p['description']))?></p><strong><?=e(money($p['price']))?></strong><a class="btn small" href="<?=e(wa_link('Bonjour, je suis intéressé par le produit '.$p['name'].'.'))?>">Commander / demander</a></article><?php endforeach;?></div><?php else:?><div class="empty"><span>Les produits seront ajoutés par l’administrateur.</span><small>Nom, photos, description, prix et disponibilité seront modifiables depuis le tableau de bord.</small></div><?php endif;?></section>
<section class="section"><span class="eyebrow">TÉMOIGNAGES</span><h2>Des expériences à découvrir</h2><?php if($testimonials):?><div class="grid three"><?php foreach($testimonials as $t):?><article><h3><?=e($t['name'])?></h3><b><?=e($t['role'])?></b><p>“<?=nl2br(e($t['content']))?>”</p></article><?php endforeach;?></div><?php else:?><div class="empty"><span>Les témoignages réels seront ajoutés par l’administrateur.</span><small>Aucun témoignage fictif n’est préinstallé.</small></div><?php endif;?></section>
<section class="section" id="formations"><span class="eyebrow">FORMATION & ACCOMPAGNEMENT</span><h2>Un accompagnement pour avancer</h2><?php if($trainings):?><div class="grid three"><?php foreach($trainings as $tr):?><article><h3><?=e($tr['title'])?></h3><p><?=nl2br(e($tr['description']))?></p><p><?=nl2br(e($tr['content']))?></p></article><?php endforeach;?></div><?php else:?><div class="empty"><span>Les formations seront ajoutées par l’administrateur.</span></div><?php endif;?></section><section id="faq" class="section"><span class="eyebrow">FAQ</span><h2>Questions fréquentes</h2><div class="faq"><?php if($faqs):foreach($faqs as $f):?><details><summary><?=e($f['question'])?></summary><p><?=nl2br(e($f['answer']))?></p></details><?php endforeach;else:?><details open><summary>Comment devenir partenaire ?</summary><p>Contactez-nous sur WhatsApp afin de découvrir le projet et les conditions de démarrage.</p></details><details><summary>Y a-t-il un accompagnement ?</summary><p>Oui, le parcours prévoit une formation et un accompagnement pour les nouveaux partenaires.</p></details><details><summary>Je veux seulement les produits, est-ce possible ?</summary><p>Oui. Vous pouvez découvrir les produits sans forcément développer l’activité.</p></details><?php endif;?></div></section>
<section class="section alt" id="contact"><span class="eyebrow">PREMIER ÉCHANGE</span><h2>Vous souhaitez en savoir plus ?</h2><div class="card"><form method="post" action="contact.php" class="grid two"><label>Prénom<input name="first_name" required></label><label>Nom<input name="last_name"></label><label>WhatsApp<input name="whatsapp" required></label><label>Je suis intéressé par<select name="interest"><option>Devenir partenaire</option><option>Les produits</option><option>Un kit de démarrage</option><option>Une formation</option><option>Autre</option></select></label><label class="full">Message<textarea name="message" placeholder="Votre question..."></textarea></label><input type="hidden" name="source" value="Site web"><button class="btn" type="submit">Envoyer ma demande</button></form></div></section><section class="cta"><div><span class="eyebrow">UNE QUESTION ?</span><h2>Parlons directement sur WhatsApp.</h2><p><?=e($phone)?></p></div><a class="btn" href="<?=e(wa_link())?>">Ouvrir WhatsApp</a></section></main><a class="wa-float" href="<?=e(wa_link())?>">WhatsApp</a><footer><span>© <?=date('Y')?> <?=e($name)?></span><a href="admin/">Administration</a></footer></body></html>
